site_name: Prise de notes Thomas Blatti
theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - header.autodhide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: black
      accent: light-gray
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: black
      accent: light-gray
nav:
  - Page d'accueil: index.md
  - Prise de notes en C: cours_info_C.md
  - Prise de notes en Python: cours_info_python.md


markdown_extensions:
  - toc:
      permalink: true
      baselevel: 3

extra_css:
  - css/custom.css 